config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'
  resources :feeds do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence:true
  validates :image, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  validates :name, presence: true, length: { maximum:30}
  validates :email, presence: true, length: { maximum:255}
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only:[:edit,:show,:update,:destroy]

  def index
    @feeds = Feed.all
  end

  def new
    if logged_in?
      @feed = Feed.new
    else
      redirect_to feeds_path, notice:"ログインしてくだい。"
    end
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    if params[:back]
      render 'new'
    else
      if @feed.save
        redirect_to feeds_path, notice:"投稿しました。"
      else
        render 'new'
      end
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    render 'new' if @feed.invalid?
  end

  def edit
    if logged_in?
      if not current_user.id == @feed.user_id
        redirect_to feeds_path, notice:"アクセス権限がありません。"
      end
    else
      redirect_to feeds_path, notice:"ログインしてください。"
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to feeds_path, notice: "編集しました。"
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    if not current_user.id == @feed.user_id
      redirect_to feeds_path, notice:"権限がありません。"
    else
      @feed.destroy
      redirect_to feeds_path, notice:"削除しました"
    end
  end


  private

  def feed_params
    params.require(:feed).permit(:image,:image_cache, :content)
  end

  def set_feed
    @feed = Feed.find_by(id: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #login
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice:"ログインしました。"
    else
      #not login
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "Sign Upしました！"
    else
      render'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<div class="form">
  <%= form_with(model: @feed, url: choose_new_or_edit,local: true) do |form| %>
    <% if @feed.errors.any? %>
      <div id="error_explanation">
        <h2><%= @feed.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @feed.errors.full_messages.each do|msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <br>
    <table>
      <div class="field">
        <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %><br>
        <tr>
          <td><%= form.label :image %></td>
          <td><%= form.file_field :image %></td>
        </tr>
        <%= form.hidden_field :image_cache %>
      </div>

      <div class="feed_content">
        <td><%= form.label :content %></td>
        <td><%= form.text_field :content %></td>
      </div>
      <tr>
        <td></td>
        <td><%= form.submit %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
    <table>
      <%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
        <%= form.hidden_field :image_cache %>
        <%= form.hidden_field :content %>
        <tr>
          <td><%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %></td>
        </tr>
        <tr>
          <td><%= @feed.content %></td>
        </tr>
        <tr>
          <td><%= form.submit "投稿する" %></td>
          <td><%= form.submit "戻る", name: "back" %></td>
        </tr>
      <% end %>
    </table>

app/views/feeds/edit.html.erb
<%= render 'form' %>

app/views/feeds/index.html.erb
<% if logged_in? %>
  <div class="new_feed">
    <%= link_to '投稿を作成する',new_feed_path %>
  </div>
<% end %>

<h1>投稿一覧</h1>

<% @feeds.each do |feed| %>
  <div class="posted_feeds">
    <table>
      <tr>
        <td>ユーザー名：<%= link_to "#{feed.user.name}", user_path(feed.user_id) %></td>
      </tr>
      <tr>
        <td>コメント：<%= feed.content %></td>
      </tr>
      <tr>
        <td><%= image_tag feed.image.url %></td>
      </tr>
    </table>
    <%= link_to "詳細", feed_path(feed.id) %>
    <% if logged_in? %>
      <% if current_user.id == feed.user_id %>
        <%= link_to "編集", edit_feed_path(feed.id) %>
        <%= link_to "削除", feed_path(feed.id), method: :delete ,data: {confirm: '本当に削除していいですか？'}%>
      <% end %>
    <% end %>
    <div class="">　</div>
    <div class="">　</div>
  </div>
<% end %>

app/views/feeds/new.html.erb
<%= render 'form' %>

app/views/feeds/show.html.erb
<p>
  <ul>
    <li><strong>Image:</strong></li>
    <li><%= image_tag @feed.image.url %></li>
    <li><strong>Content:</strong></li>
    <li><%= @feed.content %></li>
  </ul>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="menu-bar">
          <span class = "logo"><%= link_to "Clone App", feeds_path %></span>
          <div class="right">
            <% if logged_in? %>
              <span>ログイン中</span>
              <%= current_user.name %>
              <%= link_to "Profile", user_path(current_user.id) %>
              <%= link_to "Logout", session_path(current_user.id), method: :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_path %>
              <%= link_to "Login", new_session_path %>
            <% end %>
          </div>
        </div>
      </header>
      <div class="center">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
      <%= yield %>
      <footer>copyright (c)【2020】 【Facebook?】 all rights reserved.</footer>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <td><%= f.submit "Create my account" %></td>
    </tr>
  </table>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p class="center">名前: <%= @user.name %></p>
<p class="center">メールアドレス: <%= @user.email %></p>